import { HubAsset, HubEcosystemData } from "./types";

export const SAK_HUB_ASSETS: HubAsset[] = [
  // Top Featured Models (19 models in fleet)
  {
    id: "sakthai-core",
    name: "sakthai/sak-family-agent-v1",
    type: "model",
    repoId: "sakthai/sak-family-agent-v1",
    author: "sakthai",
    url: "https://huggingface.co/sakthai/sak-family-agent-v1",
    status: "active",
    meta: {
      pipelineTag: "text-generation",
      license: "apache-2.0",
      downloads: 14250,
      likes: 388,
      tags: ["sak-family", "agent-framework", "multi-persona", "th-en"],
      hasGGUF: true,
      quantizations: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    },
  },
  {
    id: "sakking-sentinel",
    name: "sakthai/sakking-sentinel-guardrails",
    type: "model",
    repoId: "sakthai/sakking-sentinel-guardrails",
    author: "sakthai",
    url: "https://huggingface.co/sakthai/sakking-sentinel-guardrails",
    status: "active",
    meta: {
      pipelineTag: "text-classification",
      license: "mit",
      downloads: 8910,
      likes: 215,
      tags: ["security", "guardrails", "ast-audit", "jailbreak-detector"],
      hasGGUF: true,
      quantizations: ["Q8_0"],
    },
  },
  {
    id: "saksee-vision",
    name: "sakthai/saksee-multimodal-ui-eval",
    type: "model",
    repoId: "sakthai/saksee-multimodal-ui-eval",
    author: "sakthai",
    url: "https://huggingface.co/sakthai/saksee-multimodal-ui-eval",
    status: "active",
    meta: {
      pipelineTag: "image-to-text",
      license: "apache-2.0",
      downloads: 6320,
      likes: 174,
      tags: ["vision", "ui-ux", "screenshot-analysis"],
      hasGGUF: false,
      quantizations: [],
    },
  },
  {
    id: "saksit-writer",
    name: "sakthai/saksit-thai-social-synthesis",
    type: "model",
    repoId: "sakthai/saksit-thai-social-synthesis",
    author: "sakthai",
    url: "https://huggingface.co/sakthai/saksit-thai-social-synthesis",
    status: "active",
    meta: {
      pipelineTag: "text-generation",
      license: "apache-2.0",
      downloads: 5120,
      likes: 129,
      tags: ["thai-nlp", "copywriting", "social-intelligence"],
      hasGGUF: true,
      quantizations: ["Q4_K_M", "Q5_K_M"],
    },
  },
  {
    id: "sakjules-cicd",
    name: "sakthai/sakjules-ci-doctor",
    type: "model",
    repoId: "sakthai/sakjules-ci-doctor",
    author: "sakthai",
    url: "https://huggingface.co/sakthai/sakjules-ci-doctor",
    status: "active",
    meta: {
      pipelineTag: "text-generation",
      license: "mit",
      downloads: 7420,
      likes: 198,
      tags: ["github-actions", "root-cause-analysis", "code-review"],
      hasGGUF: true,
      quantizations: ["Q4_K_M"],
    },
  },
  {
    id: "saktan-daily-ops",
    name: "sakthai/saktan-daily-ops-7b",
    type: "model",
    repoId: "sakthai/saktan-daily-ops-7b",
    author: "sakthai",
    url: "https://huggingface.co/sakthai/saktan-daily-ops-7b",
    status: "active",
    meta: {
      pipelineTag: "text-generation",
      license: "apache-2.0",
      downloads: 4100,
      likes: 95,
      tags: ["routine", "task-scheduling", "memory-sync"],
      hasGGUF: true,
      quantizations: ["Q4_0", "Q4_K_M"],
    },
  },
  // Datasets (16 datasets in hub)
  {
    id: "ds-sak-transcripts",
    name: "sakthai/sak-family-conversation-transcripts",
    type: "dataset",
    repoId: "sakthai/sak-family-conversation-transcripts",
    author: "sakthai",
    url: "https://huggingface.co/datasets/sakthai/sak-family-conversation-transcripts",
    status: "active",
    meta: {
      license: "cc-by-4.0",
      downloads: 12800,
      likes: 310,
      tags: ["multi-turn", "agent-transcripts", "eval"],
      hasGGUF: false,
      quantizations: [],
    },
  },
  {
    id: "ds-sentinel-eval",
    name: "sakthai/sentinel-guardrail-attack-bench",
    type: "dataset",
    repoId: "sakthai/sentinel-guardrail-attack-bench",
    author: "sakthai",
    url: "https://huggingface.co/datasets/sakthai/sentinel-guardrail-attack-bench",
    status: "active",
    meta: {
      license: "mit",
      downloads: 6400,
      likes: 180,
      tags: ["safety", "red-teaming", "jailbreak-eval"],
      hasGGUF: false,
      quantizations: [],
    },
  },
  // Spaces (7 spaces)
  {
    id: "space-dashboard",
    name: "sakthai/sak-agent-live-studio",
    type: "space",
    repoId: "sakthai/sak-agent-live-studio",
    author: "sakthai",
    url: "https://huggingface.co/spaces/sakthai/sak-agent-live-studio",
    status: "active",
    meta: {
      license: "mit",
      downloads: 3200,
      likes: 145,
      tags: ["gradio", "nextjs", "realtime-telemetry"],
      hasGGUF: false,
      quantizations: [],
    },
  },
];

export function getHubEcosystemData(): HubEcosystemData {
  return {
    totalModels: 19,
    totalDatasets: 16,
    totalSpaces: 7,
    assets: SAK_HUB_ASSETS,
    syncedAt: new Date().toISOString(),
  };
}
