/**
 * The repository's own structure, for the System view.
 *
 * Unlike every other section, this reads no runtime source: the data is a
 * snapshot of the repo generated by `scripts/gen_system_snapshot.py` and
 * committed as `src/data/system-snapshot.json`. That is what lets the hosted
 * deploy — which has no `~/.sakthai` and no live agent — show something real.
 * `meta.source_commit` says which commit it describes, so a stale snapshot is
 * visible rather than silently wrong.
 */

import raw from "@/data/system-snapshot.json";

export interface SnapshotPersona {
  name: string;
  lead: boolean;
  role: string;
  domain: string;
  provider: string | null;
  model: string | null;
  skill_count: number;
  mcp_servers: string[];
}

export interface SnapshotModule {
  name: string;
  kind: "package" | "module";
  files: number;
  lines: number;
}

export interface SnapshotTool {
  name: string;
  summary: string;
  mcp_only: boolean;
}

export interface CliNode {
  name: string;
  help: string;
  commands?: CliNode[];
}

export interface SnapshotWorkflow {
  file: string;
  name: string;
  triggers: string[];
  gates_prs: boolean;
  jobs: string[];
}

export interface SnapshotTestTree {
  name: string;
  path: string;
  files: number;
  runner: string;
}

export interface SystemSnapshot {
  meta: { source_commit: string | null; source_date: string | null; generator: string };
  personas: SnapshotPersona[];
  package: SnapshotModule[];
  tools: SnapshotTool[];
  cli: CliNode;
  workflows: SnapshotWorkflow[];
  tests: { coverage_floor: number | null; test_functions: number; trees: SnapshotTestTree[] };
  skills: { shared: string[]; library_categories: { name: string; skills: number }[] };
}

export const SYSTEM_SNAPSHOT = raw as SystemSnapshot;

/** Leaf commands — what a user can actually run — across the whole tree. */
export function countLeafCommands(node: CliNode): number {
  if (!node.commands || node.commands.length === 0) return 1;
  return node.commands.reduce((sum, child) => sum + countLeafCommands(child), 0);
}

export interface SystemTotals {
  personas: number;
  personaSkills: number;
  sharedSkills: number;
  librarySkills: number;
  tools: number;
  mcpOnlyTools: number;
  cliCommands: number;
  workflows: number;
  prWorkflows: number;
  packageLines: number;
  testFunctions: number;
  testFiles: number;
}

export function systemTotals(snapshot: SystemSnapshot): SystemTotals {
  return {
    personas: snapshot.personas.length,
    personaSkills: snapshot.personas.reduce((sum, p) => sum + p.skill_count, 0),
    sharedSkills: snapshot.skills.shared.length,
    librarySkills: snapshot.skills.library_categories.reduce((sum, c) => sum + c.skills, 0),
    tools: snapshot.tools.length,
    mcpOnlyTools: snapshot.tools.filter((t) => t.mcp_only).length,
    cliCommands: countLeafCommands(snapshot.cli),
    workflows: snapshot.workflows.length,
    prWorkflows: snapshot.workflows.filter((w) => w.gates_prs).length,
    packageLines: snapshot.package.reduce((sum, m) => sum + m.lines, 0),
    testFunctions: snapshot.tests.test_functions,
    testFiles: snapshot.tests.trees.reduce((sum, t) => sum + t.files, 0),
  };
}

/** Lines of code for one package entry, or 0 when the snapshot has none. */
export function linesOf(snapshot: SystemSnapshot, name: string): number {
  return snapshot.package.find((m) => m.name === name)?.lines ?? 0;
}
